<a href="https://colab.research.google.com/github/winwinjong-gif/Machin-Learning-report/blob/week2/EX0914_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##1. Decision Tree


import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/기계학습프로그래밍/iris.csv")

In [ ]:
X = df.drop("species", axis=1)

y = df["species"]

X

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
0                5.1             3.5              1.4             0.2
1                4.9             3.0              1.4             0.2
2                4.7             3.2              1.3             0.2
3                4.6             3.1              1.5             0.2
4                5.0             3.6              1.4             0.2
..               ...             ...              ...             ...
145              6.7             3.0              5.2             2.3
146              6.3             2.5              5.0             1.9
147              6.5             3.0              5.2             2.0
148              6.2             3.4              5.4             2.3
149              5.9             3.0              5.1             1.8

[150 rows x 4 columns]

In [ ]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = DecisionTreeClassifier()

model.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
pred_dt = model.predict(X_test)

print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       0.90      1.00      0.95         9
   virginica       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

In [ ]:
##Random Forest

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/기계학습프로그래밍/iris.csv")

In [ ]:
X=df.drop("species", axis=1)
y=df["species"]

X

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
0                5.1             3.5              1.4             0.2
1                4.9             3.0              1.4             0.2
2                4.7             3.2              1.3             0.2
3                4.6             3.1              1.5             0.2
4                5.0             3.6              1.4             0.2
..               ...             ...              ...             ...
145              6.7             3.0              5.2             2.3
146              6.3             2.5              5.0             1.9
147              6.5             3.0              5.2             2.0
148              6.2             3.4              5.4             2.3
149              5.9             3.0              5.1             1.8

[150 rows x 4 columns]

In [ ]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

model=RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
pred_rf = model.predict(X_test)

print(classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       1.00      0.89      0.94         9
   virginica       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

In [ ]:
## Logistic Regression

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/기계학습프로그래밍/iris.csv")

In [ ]:
X = df.drop("species", axis=1)
y = df["species"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
pred_lr = model.predict(X_test)

print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [ ]:
## KNN

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/기계학습프로그래밍/iris.csv")

In [ ]:
X = df.drop("species", axis=1)
y = df["species"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
model = KNeighborsClassifier(n_neighbors=5)

model.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:

pred_knn = model.predict(X_test)

print(classification_report(y_test, pred_knn))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30