<a href="https://colab.research.google.com/github/winwinjong-gif/Machin-Learning-report/blob/week2/wine_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##1. Decision Tree


import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import classification_report

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/기계학습프로그래밍/wine.csv")

In [ ]:
X=df.drop("Wine",axis=1)

y=df["Wine"]

X

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Wine, Length: 178, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
model=DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
pred_dt=model.predict(X_test)
print(classification_report(y_test,pred_dt))

              precision    recall  f1-score   support

           1       1.00      0.94      0.97        16
           2       0.80      0.92      0.86        13
           3       0.83      0.71      0.77         7

    accuracy                           0.89        36
   macro avg       0.88      0.86      0.86        36
weighted avg       0.90      0.89      0.89        36

In [ ]:
#RandomForest

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import classification_report

df=pd.read_csv("/content/drive/MyDrive/기계학습프로그래밍/wine.csv")

X=df.drop("Wine",axis=1)
y=df["Wine"]

X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

model=RandomForestClassifier()

model.fit(X_train,y_train)

pred_rf=model.predict(X_test)

print(classification_report(y_test,pred_rf))

              precision    recall  f1-score   support

           1       1.00      0.92      0.96        13
           2       0.92      1.00      0.96        11
           3       1.00      1.00      1.00        12

    accuracy                           0.97        36
   macro avg       0.97      0.97      0.97        36
weighted avg       0.97      0.97      0.97        36

In [ ]:
## Logistic Regression

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

df=pd.read_csv("/content/drive/MyDrive/기계학습프로그래밍/wine.csv")

X=df.drop("Wine",axis=1)
y=df["Wine"]

X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

model=LogisticRegression(max_iter=1000)

model.fit(X_train,y_train)

pred_lr=model.predict(X_test)

print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           1       1.00      0.90      0.95        10
           2       0.95      1.00      0.97        18
           3       1.00      1.00      1.00         8

    accuracy                           0.97        36
   macro avg       0.98      0.97      0.97        36
weighted avg       0.97      0.97      0.97        36

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
## KNN

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

df=pd.read_csv("/content/drive/MyDrive/기계학습프로그래밍/wine.csv")

X=df.drop("Wine",axis=1)
y=df["Wine"]

X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

model=KNeighborsClassifier()

model.fit(X_train,y_train)

pred_knn=model.predict(X_test)

print(classification_report(y_test,pred_knn))

              precision    recall  f1-score   support

           1       0.80      0.92      0.86        13
           2       0.55      0.50      0.52        12
           3       0.50      0.45      0.48        11

    accuracy                           0.64        36
   macro avg       0.62      0.63      0.62        36
weighted avg       0.62      0.64      0.63        36