<a href="https://colab.research.google.com/github/winwinjong-gif/Machin-Learning-report/blob/week2/week3/car_data_encodingEX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Logistic Regression

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/기계학습프로그래밍/car.data",header=None)
df
#컬럼이 없던 데이터파일을 실행하면 첫번째 데이터행이 컬럼명이 되어버림
#header=None을 파일을 불러올때 실행해야 그 다음에 컬럼명을 정해줘도 첫번째 데이터행이 사라지지 않음

          0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [ ]:
df.columns= ["buying","maint","doors","persons","lug_boot","safety","class"]
df

     buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    med  unacc
1     vhigh  vhigh      2       2    small   high  unacc
2     vhigh  vhigh      2       2      med    low  unacc
3     vhigh  vhigh      2       2      med    med  unacc
4     vhigh  vhigh      2       2      med   high  unacc
...     ...    ...    ...     ...      ...    ...    ...
1722    low    low  5more    more      med    med   good
1723    low    low  5more    more      med   high  vgood
1724    low    low  5more    more      big    low  unacc
1725    low    low  5more    more      big    med   good
1726    low    low  5more    more      big   high  vgood

[1727 rows x 7 columns]

In [ ]:
label_encoders = {}

for column in df.columns:

    label_encoders[column] = LabelEncoder()

    df[column] = label_encoders[column].fit_transform(df[column])

X=df.drop("class",axis=1)
y=df["class"]
print(X)
print(y)

      buying  maint  doors  persons  lug_boot  safety
0          3      3      0        0         2       2
1          3      3      0        0         2       0
2          3      3      0        0         1       1
3          3      3      0        0         1       2
4          3      3      0        0         1       0
...      ...    ...    ...      ...       ...     ...
1722       1      1      3        2         1       2
1723       1      1      3        2         1       0
1724       1      1      3        2         0       1
1725       1      1      3        2         0       2
1726       1      1      3        2         0       0

[1727 rows x 6 columns]
0       2
1       2
2       2
3       2
4       2
       ..
1722    1
1723    3
1724    2
1725    1
1726    3
Name: class, Length: 1727, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
model=LogisticRegression(max_iter=1000)

model.fit(X_train,y_train)
pred_lr=model.predict(X_test)
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.38      0.25      0.30        73
           1       0.00      0.00      0.00        15
           2       0.75      0.92      0.83       239
           3       0.38      0.16      0.22        19

    accuracy                           0.69       346
   macro avg       0.38      0.33      0.34       346
weighted avg       0.62      0.69      0.65       346

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
# Decision Tree Classification

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

df = pd.read_csv(
    "/content/drive/MyDrive/기계학습프로그래밍/car.data",
    header=None
)

df.columns = [
    "buying", "maint", "doors", "persons",
    "lug_boot", "safety", "class"
]

# Label Encoding
label_encoders = {}

for column in df.columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

# X, y 분리
X = df.drop("class", axis=1)
y = df["class"]

print(X)
print(y)

# Train / Test 분리
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

# Decision Tree 모델
model = DecisionTreeClassifier()

model.fit(X_train, y_train)

pred_dt = model.predict(X_test)

print(classification_report(y_test, pred_dt))

      buying  maint  doors  persons  lug_boot  safety
0          3      3      0        0         2       1
1          3      3      0        0         2       2
2          3      3      0        0         2       0
3          3      3      0        0         1       1
4          3      3      0        0         1       2
...      ...    ...    ...      ...       ...     ...
1723       1      1      3        2         1       2
1724       1      1      3        2         1       0
1725       1      1      3        2         0       1
1726       1      1      3        2         0       2
1727       1      1      3        2         0       0

[1728 rows x 6 columns]
0       2
1       2
2       2
3       2
4       2
       ..
1723    1
1724    3
1725    2
1726    1
1727    3
Name: class, Length: 1728, dtype: int64
              precision    recall  f1-score   support

           0       1.00      0.97      0.99        79
           1       1.00      1.00      1.00         6
           2       0.99      1.00      1.00       247
           3       1.00      1.00      1.00        14

    accuracy                           0.99       346
   macro avg       1.00      0.99      1.00       346
weighted avg       0.99      0.99      0.99       346

In [ ]:
# KNN Classification

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

df = pd.read_csv(
    "/content/drive/MyDrive/기계학습프로그래밍/car.data",
    header=None
)

df.columns = [
    "buying", "maint", "doors", "persons",
    "lug_boot", "safety", "class"
]

# Label Encoding
label_encoders = {}

for column in df.columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

# X, y 분리
X = df.drop("class", axis=1)
y = df["class"]

print(X)
print(y)

# Train / Test 분리
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

# KNN 모델
model = KNeighborsClassifier(n_neighbors=5)

model.fit(X_train, y_train)

pred_knn = model.predict(X_test)

print(classification_report(y_test, pred_knn))

      buying  maint  doors  persons  lug_boot  safety
0          3      3      0        0         2       1
1          3      3      0        0         2       2
2          3      3      0        0         2       0
3          3      3      0        0         1       1
4          3      3      0        0         1       2
...      ...    ...    ...      ...       ...     ...
1723       1      1      3        2         1       2
1724       1      1      3        2         1       0
1725       1      1      3        2         0       1
1726       1      1      3        2         0       2
1727       1      1      3        2         0       0

[1728 rows x 6 columns]
0       2
1       2
2       2
3       2
4       2
       ..
1723    1
1724    3
1725    2
1726    1
1727    3
Name: class, Length: 1728, dtype: int64
              precision    recall  f1-score   support

           0       0.86      0.80      0.83        74
           1       1.00      0.45      0.62        11
           2       0.93      0.99      0.96       246
           3       1.00      0.73      0.85        15

    accuracy                           0.92       346
   macro avg       0.95      0.74      0.81       346
weighted avg       0.92      0.92      0.91       346

In [ ]:
# Random Forest Classification

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

df = pd.read_csv(
    "/content/drive/MyDrive/기계학습프로그래밍/car.data",
    header=None
)

df.columns = [
    "buying", "maint", "doors", "persons",
    "lug_boot", "safety", "class"
]

# Label Encoding
label_encoders = {}

for column in df.columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

# X, y 분리
X = df.drop("class", axis=1)
y = df["class"]

print(X)
print(y)

# Train / Test 분리
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

# Random Forest 모델
model = RandomForestClassifier()

model.fit(X_train, y_train)

pred_rf = model.predict(X_test)

print(classification_report(y_test, pred_rf))

      buying  maint  doors  persons  lug_boot  safety
0          3      3      0        0         2       1
1          3      3      0        0         2       2
2          3      3      0        0         2       0
3          3      3      0        0         1       1
4          3      3      0        0         1       2
...      ...    ...    ...      ...       ...     ...
1723       1      1      3        2         1       2
1724       1      1      3        2         1       0
1725       1      1      3        2         0       1
1726       1      1      3        2         0       2
1727       1      1      3        2         0       0

[1728 rows x 6 columns]
0       2
1       2
2       2
3       2
4       2
       ..
1723    1
1724    3
1725    2
1726    1
1727    3
Name: class, Length: 1728, dtype: int64
              precision    recall  f1-score   support

           0       0.96      0.96      0.96        72
           1       0.82      0.90      0.86        10
           2       1.00      0.99      0.99       252
           3       1.00      1.00      1.00        12

    accuracy                           0.98       346
   macro avg       0.94      0.96      0.95       346
weighted avg       0.98      0.98      0.98       346